
version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: opencloud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

clientId-github: Ov23liJUf2kWNAb2sv5C
clientSecret-github: 78a2b5caaf24651036bdd1c56e7b60342fed01f7